### PR TITLE
Add github-namecheck flag

### PR DESCRIPTION
**Pull request by liyanchang**
Two features required for this:
1. The ability to make a new http request to get a users info
2. The ability to page through multiple results (techically we
probably needed this for 2fa checks as well but we never had more than
30 people who didn't have 2fa enabled)

This (and I suppose a previous commit to this project) is the only rust I've done so would appreciate any code review and comments!

### CODE REVIEW

**Comment by alex** [comment]
Not sure what I think, this expands the scope of `otp-cop` a bit.

On a substantive note, I ran a `cargo update` on `master`, with the hopes of decreasing the size of this PR, but it also generated some merge conflicts.

**Comment by liyanchang** [comment]
Yup. So the two downsides:
1. It's expands scope to name check.
2. Big performance hit - we go from 1 http call to check github 2fa to 1+number of users who don't have 2fa calls. If you're doing namecheck, it's linear with the number of users in your org.

I think it's handy for me to help bug people about setting a name - that's arguably a niche use case.

**Comment by liyanchang** [comment]
Rebased to remove merge conflicts.

**Comment by liyanchang** [comment]
I don't think it's a big deal either way. If you would like to keep this project finely scoped, I'll just keep it on a branch for personal use.

**Pull request closed without merging**
